on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GHACTIONS_DEST_HOST }}
          username: ${{ secrets.GHACTIONS_USER }}
          key: ${{ secrets.GHACTIONS_PRIVATE_KEY }}
          port: ${{ secrets.GHACTIONS_PORT }}
          script: |
            set -e  # Detener el script si ocurre un error
            cd ${{ secrets.GHACTIONS_WORK_DIR }}
            git reset --hard
            git pull origin ${{ secrets.GHACTIONS_BRANCH }} || { echo "Error: git pull falló"; exit 1; }
            echo "Repositorio sincronizado correctamente"

      - name: copy .env file
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GHACTIONS_DEST_HOST }}
          username: ${{ secrets.GHACTIONS_USER }}
          key: ${{ secrets.GHACTIONS_PRIVATE_KEY }}
          port: ${{ secrets.GHACTIONS_PORT }}
          script: |
            set -e
            cd ${{ secrets.GHACTIONS_WORK_DIR }}
            cp ../.env .env
            echo "Archivo .env copiado correctamente"

      - name: restart application with PM2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GHACTIONS_DEST_HOST }}
          username: ${{ secrets.GHACTIONS_USER }}
          key: ${{ secrets.GHACTIONS_PRIVATE_KEY }}
          port: ${{ secrets.GHACTIONS_PORT }}
          script: |
            set -e
            pm2 -v
            export PATH="$PATH:$(npm config get prefix)/bin"
            pm2 -v
            pm2 restart backend || pm2 start bun --name backend -- run dev
            echo "Aplicación reiniciada correctamente"
